apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-controller-manager
  namespace: DESIRED_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-leader-election-role
  namespace: DESIRED_NAMESPACE
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    name: splunk-operator
  name: splunk-operator-manager-role
  namespace: DESIRED_NAMESPACE
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - monitoringconsoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - monitoringconsoles/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - monitoringconsoles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - standalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - standalones/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - standalones/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-leader-election-rolebinding
  namespace: DESIRED_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: splunk-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: splunk-operator-controller-manager
  namespace: DESIRED_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-manager-rolebinding
  namespace: DESIRED_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: splunk-operator-manager-role
subjects:
- kind: ServiceAccount
  name: splunk-operator-controller-manager
  namespace: DESIRED_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: splunk-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: splunk-operator-controller-manager
  namespace: DESIRED_NAMESPACE
---
apiVersion: v1
data:
  OPERATOR_NAME: '"splunk-operator"'
  RELATED_IMAGE_SPLUNK_ENTERPRISE: SPLUNK_IMAGE
  WATCH_NAMESPACE: ""
kind: ConfigMap
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-config
  namespace: DESIRED_NAMESPACE
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 270bec8c.splunk.com
kind: ConfigMap
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-manager-config
  namespace: DESIRED_NAMESPACE
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    name: splunk-operator
  name: splunk-operator-controller-manager-metrics-service
  namespace: DESIRED_NAMESPACE
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
    name: splunk-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    name: splunk-operator
  name: splunk-operator-controller-manager-service
  namespace: DESIRED_NAMESPACE
spec:
  ports:
  - name: metric
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: health
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    control-plane: controller-manager
    name: splunk-operator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-app-download
  namespace: DESIRED_NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    name: splunk-operator
  name: splunk-operator-controller-manager
  namespace: DESIRED_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: splunk-operator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        kubectl.kubernetes.io/default-logs-container: manager
      labels:
        control-plane: controller-manager
        name: splunk-operator
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      - args:
        - --leader-elect
        - --pprof
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_SPLUNK_ENTERPRISE
          valueFrom:
            configMapKeyRef:
              name: splunk-operator-config
              key: RELATED_IMAGE_SPLUNK_ENTERPRISE
        - name: OPERATOR_NAME
          value: splunk-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: quay.io/fuse_qe/splunk-operator:2.0.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 1000m
            memory: 2000Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /opt/splunk/appframework/
          name: app-staging
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccountName: splunk-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: splunk-operator-config
        name: splunk-operator-config
      - name: app-staging
        persistentVolumeClaim:
          claimName: splunk-operator-app-download
