package org.jboss.fuse.tnb.product.standalone.application;

import org.jboss.fuse.tnb.common.config.TestConfiguration;
import org.jboss.fuse.tnb.common.utils.IOUtils;
import org.jboss.fuse.tnb.product.application.App;
import org.jboss.fuse.tnb.product.integration.IntegrationBuilder;
import org.jboss.fuse.tnb.product.integration.IntegrationGenerator;
import org.jboss.fuse.tnb.product.log.MavenLog;
import org.jboss.fuse.tnb.product.util.maven.BuildRequest;
import org.jboss.fuse.tnb.product.util.maven.Maven;

import org.apache.maven.model.Dependency;
import org.apache.maven.model.Model;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class StandaloneApp extends App {
    private static final Logger LOG = LoggerFactory.getLogger(StandaloneApp.class);

    private final ExecutorService executorService = Executors.newFixedThreadPool(1);
    private BuildRequest buildRequest;
    boolean isRunning = true;

    public StandaloneApp(IntegrationBuilder integrationBuilder) {
        super(integrationBuilder.getIntegrationName());

        LOG.info("Creating Camel Standalone application project for integration {}", name);
        if (!TestConfiguration.appLocation().resolve(TestConfiguration.appTemplateName()).toFile().exists()) {
            IOUtils.createDirectory(TestConfiguration.appLocation());

            LOG.debug("Creating standalone app template in {}", TestConfiguration.appLocation().toAbsolutePath());
            Maven.invoke(new BuildRequest.Builder()
                .withBaseDirectory(TestConfiguration.appLocation())
                .withGoals("archetype:generate")
                .withProperties(Map.of(
                    "archetypeGroupId", "org.apache.camel.archetypes",
                    "archetypeArtifactId", "camel-archetype-main",
                    "archetypeVersion", TestConfiguration.camelArchetypeVersion(),
                    "groupId", TestConfiguration.appGroupId(),
                    "artifactId", TestConfiguration.appTemplateName()))
                .withLogFile(TestConfiguration.appLocation().resolve("app-template-generate.log"))
                .build()
            );
        }

        IOUtils.createDirectory(TestConfiguration.appLocation().resolve(name));
        IOUtils.copyDirectory(TestConfiguration.appLocation().resolve(TestConfiguration.appTemplateName()),
            TestConfiguration.appLocation().resolve(name));

        IntegrationGenerator.toFile(integrationBuilder, TestConfiguration.appLocation().resolve(name));

        customizeProject(integrationBuilder.getDependencies());
    }

    @Override
    public void start() {
        buildRequest = new BuildRequest.Builder()
            .withBaseDirectory(TestConfiguration.appLocation().resolve(name))
            .withGoals("compile", "camel:run")
            .withLogFile(TestConfiguration.appLocation().resolve(name + ".log"))
            .build();

        log = new MavenLog(buildRequest.getOutputHandler());

        executorService.submit(() -> {
            try {
                Maven.invoke(buildRequest);
            } catch (Exception e) {
                LOG.error("Error while running app: ", e);
            } finally {
                isRunning = false;
            }
        });
    }

    @Override
    public void stop() {
        executorService.shutdownNow();
    }

    @Override
    public boolean isReady() {
        return isRunning && isCamelStarted();
    }

    @Override
    public boolean isFailed() {
        return !isRunning;
    }

    /**
     * Customizes the project generated by the archetype to TNB app needs.
     *
     * @param dependencies dependencies to add to the project
     */
    private void customizeProject(List<String> dependencies) {
        if (dependencies == null || dependencies.isEmpty()) {
            return;
        }
        File pom = TestConfiguration.appLocation().resolve(name).resolve("pom.xml").toFile();

        Model model = Maven.loadPom(pom);
        dependencies.forEach(dep -> model.getDependencies().add(Maven.toDependency(dep)));
        final Dependency camelBom = model.getDependencyManagement().getDependencies().stream()
            .filter(d -> "camel-bom".equals(d.getArtifactId())).findFirst().get();
        camelBom.setVersion(TestConfiguration.camelVersion());
        Maven.writePom(pom, model);
    }
}
