name: Checkstyle
on:
  pull_request_target
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.6.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          checkstyle_config: checkstyle/checkstyle.xml
